### PR TITLE
Google Spreadsheets, Audio, Chrome Sync, Bug fixes

### PR DESCRIPTION
**Pull request by aragonsr**
Features:
**Importing Google Spreadsheet Data**
    - User can now import large amounts of vocab words using google spreadsheets.
    - This allows users to share their vocab lists.
    - Importing from Google Spreadsheets overrides the WaniKani vocab.
    - Shows the total number of entries that have been imported. Which could be multiple synonyms.

**Custom Vocab Override**
    - User can now override WaniKani vocab entries AND "Google spreadsheets import" using the custom vocab box.
    - Or if they just want to add a few extra vocab words easily, they can also use it for that too.
    - This is meant as a quick and dirty way to add your own custom vocab easily without setting up a google spreadsheet.
    - For example, "times" gets translated as "〜回" from WaniKani, which is silly. So you can use this to override it to just "回" if you want.
    - This is not meant for large amounts of vocab since it is also synced using Google Sync.

**Google Chrome Sync**
    - Settings for wanikanify now are persistence across computers if user has Chrome's sync functionality enabled.
    - Note the vocab data is not synced because it's too much data. But the settings are synced, so you'll just have to click the "import" buttons again for Google Spreadsheets.

**Audio**
    - Mousing over (or clicking) a word will play the audio for that word from HTML5's built-in speech synthesis.
    - This works very well as a learning tool in combination with rikaikun.
    - It's possible the audio played could not be correct if the readings are missing from the spreadsheets, but it will try to play it anyways.
    - Put in option to disable the audio functionality and change whether it's on click or on hover.
    - Custom vocab can also use readings for audio.

### CODE REVIEW

**Comment by aragonsr** [comment]
There are a bunch of what looks like duplicate commits. I tried to run a script to change my email address, but it just ended up making a bunch of duplicate commits. Oh well, nothing changed.

**Comment by josefalcon** [comment]
@aragonsr whoa! this is a ton of work! looks super cool. reviewing it now.

**Comment by josefalcon** [comment]
@aragonsr This is great! Two things: Can you update the README with all the features? Is there anyway to resolve all the duplicate commits? If not, no worries.

**Comment by aragonsr** [comment]
Well, I'll see about the duplicate commits.. I'm not sure. I think it's possible.
I'll update the readme.
Also, there's probably a lot of better ways to do things and some duplicate code in places. :-/ It can be improved a lot.

**Comment by aragonsr** [comment]
I fixed the duplicate commits. Readme also updated.

**Comment by josefalcon** [comment]
Great! Will merge and release this as soon as possible.

**Comment by aragonsr** [comment]
Okay great.
I tried to get people on wanikani forums to test it, but I didn't get much response.

**Comment by josefalcon** [comment]
@aragonsr Pushed the latest version to the Chrome Web Store!

**Comment by aragonsr** [comment]
Awesome. Thanks.
When I tested it the audio was broken on windows.
So I created another pull request for you to review. :) My bad.

-Todd

Todd Seiler
425.214.6519
todd.seiler@gmail.com
http://www.toddseiler.com

**Comment by aragonsr** [comment]
Something is wrong with the blacklist ...
I'm looking into it.

Todd Seiler
425.214.6519
todd.seiler@gmail.com
http://www.toddseiler.com

**Comment by aragonsr** [comment]
Okay. I fixed the blacklist issue.

On Wednesday, August 26, 2015, Todd Seiler <todd.seiler@gmail.com> wrote:

> Something is wrong with the blacklist ...
> I'm looking into it.
>
> Todd Seiler
> 425.214.6519
> todd.seiler@gmail.com
> <javascript:_e(%7B%7D,'cvml','todd.seiler@gmail.com');>
> http://www.toddseiler.com
>
> On Wed, Aug 26, 2015 at 7:44 PM, Todd Seiler <todd.seiler@gmail.com
> <javascript:_e(%7B%7D,'cvml','todd.seiler@gmail.com');>> wrote:
>
>> Awesome. Thanks.
>> When I tested it the audio was broken on windows.
>> So I created another pull request for you to review. :) My bad.
>>
>> -Todd
>>
>> Todd Seiler
>> 425.214.6519
>> todd.seiler@gmail.com
>> <javascript:_e(%7B%7D,'cvml','todd.seiler@gmail.com');>
>> http://www.toddseiler.com
>>
>> On Wed, Aug 26, 2015 at 6:15 PM, Jose Falcon <notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>
>>> @aragonsr <https://github.com/aragonsr> Pushed the latest version to
>>> the Chrome Web Store!
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/josefalcon/wanikanify/pull/3#issuecomment-135202947>
>>> .
>>>
>>
>>
>

-- 
Todd Seiler
425.214.6519
todd.seiler@gmail.com
http://www.toddseiler.com

**Pull request merged**
